
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Créer une instance Supabase avec des valeurs sécurisées
export const supabase = createClient(
  'https://erhkxltscmezrsnpwygd.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyaGt4bHRzY21lenJzbnB3eWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjUzMzUsImV4cCI6MjA2MDEwMTMzNX0.Tks0g_4mWlRJ_QiZL9E-TI9ShkBxBeEhlW-F_bpg6eo',
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);

// Type assertion to completely bypass type checking
// This is necessary until tables are properly set up in Supabase and types are generated
const supabaseAny = supabase as any;

// Fonctions utilitaires pour interagir avec Supabase
export const supabaseClient = {
  // Auth helpers
  auth: {
    signUp: async (email: string, password: string, metadata?: object) => {
      return await supabase.auth.signUp({ 
        email, 
        password, 
        options: { data: metadata } 
      });
    },
    signIn: async (email: string, password: string) => {
      return await supabase.auth.signInWithPassword({ email, password });
    },
    signOut: async () => {
      return await supabase.auth.signOut();
    },
    getCurrentUser: async () => {
      return await supabase.auth.getUser();
    },
    getSession: async () => {
      return await supabase.auth.getSession();
    },
    resetPassword: async (email: string) => {
      return await supabase.auth.resetPasswordForEmail(email);
    },
    onAuthStateChange: (callback: (event: any, session: any) => void) => {
      return supabase.auth.onAuthStateChange(callback);
    }
  },
  
  // Storage helpers
  storage: {
    uploadFile: async (bucket: string, path: string, file: File) => {
      return await supabase.storage.from(bucket).upload(path, file);
    },
    getPublicUrl: (bucket: string, path: string) => {
      return supabase.storage.from(bucket).getPublicUrl(path);
    },
    deleteFile: async (bucket: string, path: string) => {
      return await supabase.storage.from(bucket).remove([path]);
    },
    listFiles: async (bucket: string, path?: string) => {
      return await supabase.storage.from(bucket).list(path);
    }
  },
  
  // Database helpers
  db: {
    // Generic query helper with complete type bypass
    from: (table: string) => {
      // Using supabaseAny to completely bypass type checking
      return supabaseAny.from(table);
    },
    
    // Customers query with complete type assertion
    getCustomers: async () => {
      // Using supabaseAny to completely bypass type checking
      return await supabaseAny.from('profiles').select('*');
    },
    
    // Orders query with complete type assertion
    getOrders: async () => {
      // Using supabaseAny to completely bypass type checking
      return await supabaseAny.from('orders').select('*');
    },
    
    // Products query with complete type assertion
    getProducts: async () => {
      // Using supabaseAny to completely bypass type checking
      return await supabaseAny.from('products').select('*');
    },
    
    // Add more specific database helpers as needed
  }
};
